# Generated by Django 2.2.19 on 2023-04-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230423_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_of_measurement',
            new_name='measurement_unit',
        ),
    ]
