# Generated by Django 2.2.19 on 2023-05-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230429_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hexcolor',
            new_name='color',
        ),
    ]
