# Generated by Django 2.2.19 on 2023-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230429_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='hexcolor',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=0, help_text='Выберите цвет', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
